app = "devops-production"

[build]
  image = "x7m7s7/devops:latest"

[http_service]
  internal_port = 5000
  force_https = true  
  
[env]
  PORT = "5000"

[processes]
  app = "gunicorn -w 1 -b 0.0.0.0:5000 app:app"
